### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by Amri95** [luishowell/ecg-detectors#1]
Hi there, thankyou for your source code ! The data you are using is in .tsv format. 
I am taking the .csv data (single ECG column) of 10sec with total of 1280 samples with sampling  freq = 128 Hz.

I am getting the the following index error-
"too many indices for array".

With regards

**Comment by luishowell** [comment]
Hi Amri95, could you show me the snippet of your code that isn't working? Which detector function are you trying to use?

**Comment by Amri95** [comment]
I have taken the ECG sample from MIT-Normal sinus rhythm Database of a
single lead which is 1min long and Fs=128. The sample ecg and the error are
in the attached file. I want to apply the Christov detector.
Thank you !

**Comment by luishowell** [comment]
Hi, I couldn't see your attached file but I downloaded the MIT-Normal sinus rhythm Database and it works without issue for me:

```python
sig, fields = wfdb.rdsamp(r'C:\Users\Luis\Downloads\16265')
unfiltered_ecg = sig[:3000, 0]     
fs = 128

detectors = Detectors(fs)
r_peaks = detectors.christov_detector(unfiltered_ecg)

plt.figure()
plt.plot(unfiltered_ecg)
plt.plot(r_peaks, unfiltered_ecg[r_peaks], 'ro')
plt.title('Detected R-peaks')
plt.show()
```
![](https://i.ibb.co/6ZcZydr/Figure-1.png)
I believe your issue is that you are not selecting a single coloumn of data.

**Comment by Amri95** [comment]
Sorry to bother you again. I think I am having trouble accessing the data
at first.
Again I am sending the sample data. I am only taking one lead i,e, ECG1
from the 16265 records. The record is in the CSV format.
Please correct me if I am wrong. And thank you so much for your response.

KInd regards

**Comment by luishowell** [comment]
You can't attach a file if you are replying with email. Can you go onto the [issue on Github](https://github.com/luishowell/ecg-detectors/issues/1) and upload a zip file containing your code and the csv file.

**Comment by Amri95** [comment]
[normal_16265.zip](https://github.com/luishowell/ecg-detectors/files/2855972/normal_16265.zi

**Comment by luishowell** [comment]
Your csv file has labels in the first two rows, remove those and you can load it as so:

```python
unfiltered_ecg = np.loadtxt(r'C:\Users\Luis\Downloads\normal_16265.csv')
fs = 128

detectors = Detectors(fs)

r_peaks = detectors.christov_detector(unfiltered_ecg)

plt.figure()
plt.plot(unfiltered_ecg)
plt.plot(r_peaks, unfiltered_ecg[r_peaks], 'ro')
plt.title('Detected R-peaks')
plt.show()
```

This works for me.

**Comment by Amri95** [comment]
> Your csv file has labels in the first two rows, remove those and you can load it as so:
> 
> ```python
> unfiltered_ecg = np.loadtxt(r'C:\Users\Luis\Downloads\normal_16265.csv')
> fs = 128
> 
> detectors = Detectors(fs)
> 
> r_peaks = detectors.christov_detector(unfiltered_ecg)
> 
> plt.figure()
> plt.plot(unfiltered_ecg)
> plt.plot(r_peaks, unfiltered_ecg[r_peaks], 'ro')
> plt.title('Detected R-peaks')
> plt.show()
> ```
> 
> This works for me.

Thanks a lot !
